[package]
name = "fastly-opentelemetry"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
fastly.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk = { workspace = true, features = ["trace"] }
tracing.workspace = true
